# ACCESS_TOKEN = "SEU_ACCESS_TOKEN_DO_TWITTER_API_AQUI"
# ACCESS_TOKEN_SECRET = "SEU_ACCESS_TOKEN_DO_TWITTER_API_AQUI"

# CONSUMER_KEY = "SEU_CONSUMER_KEY_DO_TWITTER_API_AQUI"
# CONSUMER_SECRET = "SEU_CONSUMER_SECRET_DO_TWITTER_API_AQUI"

